site_name: LaHMG Docs
site_description: 'Documentation for Louisiana Historical Map Georeferencer'
site_author: 'mradamcox'
site_url: https://oldinsurancemaps.net

# repo_url: https://github.com/mradamcox/loc-insurancemaps
toc_info: true

dev_addr: '127.0.0.1:8001'

nav:
  - Overview: overview.md
  # - Sanborn Maps: sanborn-maps.md
  - Georeferencing Process: georeferencing-process.md
  # - Tutorial: tutorial.md
  - Extra Info: extra.md

theme:
  name: 'custommill'
  home: overview
  main_color: '#123B4F'
  lighter_gray: '#EAE0C1'
  toc_depth: 1

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - markdown_captions
  - footnotes

extra_css: 
  - css/custom.css

extra:
  version: 0.1
  nav_links:
  - icon: home
    text: Go to LaHMG &rarr;
    url: https://oldinsurancemaps.net
  - icon: code-branch
    text: Source Code
    url: https://github.com/mradamcox/loc-insurancemaps
  - icon: map
    text: LOC Sanborn Maps
    url: https://loc.gov/collections/sanborn-maps